version: '3.8'

services:
  db:
    build:
      context: ./db
    container_name: local-siop-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: siop-db
      MYSQL_USER: dev
      MYSQL_PASSWORD: 1105
    networks:
      - test
    ports:
      - "4510:3306"
    healthcheck: # MySQL 초기화 확인
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "dev", "-p1105"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./backend/sucpi
    container_name: siop-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://local-siop-db:3306/siop-db
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: 1105
    depends_on:
      db:
        condition: service_healthy # MySQL이 준비되면 시작
    networks:
      - test
    ports:
      - "4502:8080"

  frontend:
    build:
      context: ./frontend/sucpi
    container_name: siop-frontend
    ports:
      - "4501:3000"
    networks:
      - test
    environment:
        # 로컬 서버
        VIRTUAL_HOST: frontend.localhost

        # 개발 서버
        # VIRTUAL_HOST : 사용자가 접근할 도메인 이름 설정
        # LETSENCRYPT_HOST : 해당 도메인의 SSL 인증서를 발급받기 위한 도메인 이름
        # VIRTUAL_HOST: "siop-dev.skku.edu"
        # LETSENCRYPT_HOST: "siop-dev.skku.edu"

        VIRTUAL_PORT: 3000
    extra_hosts: 
        - host.docker.internal:host-gateway
    command: ["npm", "start"]

  # 로컬 서버
  nginx:
    build:
      context: ./nginx
    container_name: siop-nginx
    ports:
      - "80:80"
    networks:
      - test
    depends_on:
      - backend

networks:
  test:
    driver: bridge
