# MySQL 공식 이미지를 기반으로 사용
FROM mysql:8.0

# MySQL 환경 변수 설정
ENV MYSQL_ROOT_PASSWORD=1234 \
    MYSQL_DATABASE=siop-db \
    MYSQL_USER=siop-dev \
    MYSQL_PASSWORD=siop123!!!

# MySQL 기본 포트 노출
EXPOSE 3306