INSERT INTO LQ_Weight (id, dataname, name, weight) VALUES
(1, 'lqEduActivity1', '교내외 교육활동', 0),
(2, 'lqEduActivity2', '교육조교 활동', 0),
(3, 'lqGrade40TO45', '학점 4.0~4.5', 0),
(4, 'lqGrade35TO40', '학점 3.5~4.0', 0),
(5, 'lqGrade30TO35', '학점 3.0~3.5', 0),
(6, 'lqOpenSourceActivity1Star1', '오픈소스 커뮤니티 생성 및 활성도 1점', 0),
(7, 'lqOpenSourceActivity1Star2', '오픈소스 커뮤니티 생성 및 활성도 2점', 0),
(8, 'lqOpenSourceActivity1Star3', '오픈소스 커뮤니티 생성 및 활성도 3점', 0),
(9, 'lqOpenSourceActivity1Star4', '오픈소스 커뮤니티 생성 및 활성도 4점', 0),
(10, 'lqOpenSourceActivity1Star5', '오픈소스 커뮤니티 생성 및 활성도 5점', 0),
(11, 'lqOpenSourceActivity2Star1', '커미터로서의 활동 1점', 0),
(12, 'lqOpenSourceActivity2Star2', '커미터로서의 활동 2점', 0),
(13, 'lqOpenSourceActivity2Star3', '커미터로서의 활동 3점', 0),
(14, 'lqOpenSourceActivity2Star4', '커미터로서의 활동 4점', 0),
(15, 'lqOpenSourceActivity2Star5', '커미터로서의 활동 5점', 0);

INSERT INTO RQ_Weight (id, dataname, name, weight) VALUES
(1, 'rqYulJcr5Main', '율전 JCR 5% 주저', 0),
(2, 'rqYulJcr5Part', '율전 JCR 5% 공저', 0),
(3, 'rqYulJcr10Main', '율전 JCR 10% 주저', 0),
(4, 'rqYulJcr10Part', '율전 JCR 10% 공저', 0),
(5, 'rqYulJcr20Main', '율전 JCR 20% 주저', 0),
(6, 'rqYulJcr20Part', '율전 JCR 20% 공저', 0),
(7, 'rqYulKnownSpeech', '율전 저명 국제학술 발표 구두', 0),
(8, 'rqYulKnownPoster', '율전 저명 국제학술 발표 포스터', 0),
(9, 'rqYulNormalSpeech', '율전 일반 국제학술 발표 구두', 0),
(10, 'rqYulNormalPoster', '율전 일반 국제학술 발표 포스터', 0),
(11, 'rqYulNationalSpeech', '율전 국내학술 발표 구두', 0),
(12, 'rqYulNationalPoster', '율전 국내학술 발표 포스터', 0),
(13, 'rqYulWinBigCompetition', '율전 국제/대규모 공모전 입상', 0),
(14, 'rqYulPlayBigCompetition', '율전 국제/대규모 공모전 참여', 0),
(15, 'rqYulWinSchoolCompetition', '율전 교내/지역 공모전 입상', 0),
(16, 'rqYulPlaySchoolCompetition', '율전 교내/지역 공모전 참여', 0),
(17, 'rqMyeongOverKci', '명륜 SCI, SSCI, A&HCI급 학술지', 0),
(18, 'rqMyeongKciExcellent', '명륜 KCI 우수등재', 0),
(19, 'rqMyeongKci', '명륜 KCI 등재', 0),
(20, 'rqMyeongKciCandidate', '명륜 KCI 후보, 기타 국제', 0),
(21, 'rqMyeongKnownSpeech', '명륜 저명 국제학술 대회 발표', 0),
(22, 'rqMyeongNormalSpeech', '명륜 일반 국제학술 대회 발표', 0),
(23, 'rqMyeongNationalSpeech', '명륜 국내학술 대회 발표', 0),
(24, 'rqMyeongBigCompetition', '명륜 국제/대규모 공모전', 0),
(25, 'rqMyeongSchoolCompetition', '명륜 교내/지역 공모전', 0);

INSERT INTO CQ_Weight (id, dataname, name, weight) VALUES
(1, 'cqCoop', '산학협력', 0),
(2, 'cqInternship', '인턴십', 0),
(3, 'cqStartup', '창업', 0),
(4, 'cqOverseaVolunteer', '해외봉사', 0),
(5, 'cqLectureSeminar', '화상강연/세미나', 0),
(6, 'cqAlimi', '알리미', 0),
(7, 'cqStudentCouncil', '학생회', 0),
(8, 'cqMediaPromotion', '미디어 홍보', 0),
(9, 'cqStudioContribution', '미디어 갤러리 참여', 0),
(10, 'cqStudyGroup', '스터디 그룹', 0);